name: flutter_image_utils_example
description: Demonstrates how to use the flutter_image_utils plugin.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_image_utils:
    path: ../

flutter:
  uses-material-design: true
