name: flutter_image_utils
description: Flutter plugin for image cropping, resizing and rotation implemented in native languages both for iOS and Android. Provides zero platform configuration, simple API, speed and quality of produced images
version: 0.1.0
author: vanelizarov<elizarov.vanya@gmail.com>
homepage: https://github.com/vanelizarov/flutter_image_utils

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^0.6.0+3

flutter:
  plugin:
    androidPackage: com.vanelizarov.flutter_image_utils
    pluginClass: FlutterImageUtilsPlugin
